import 'dotenv/config';
import crypto from 'node:crypto';
import express from 'express';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import Stripe from 'stripe';
import { createClient } from '@supabase/supabase-js';
import { claimStripeWebhook, completeStripeWebhook, failStripeWebhook } from './lib/stripe-webhook-state.js';

const __dirname=path.dirname(fileURLToPath(import.meta.url));
const app=express(); const port=Number(process.env.PORT||3000);
const appUrl=(process.env.APP_URL||`http://localhost:${port}`).replace(/\/$/,'');
const supabasePublicKey=process.env.SUPABASE_PUBLISHABLE_KEY||process.env.SUPABASE_ANON_KEY||'';
const supabaseSecretKey=process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY||'';
const hasPublic=Boolean(process.env.SUPABASE_URL&&supabasePublicKey);
const hasAdmin=Boolean(hasPublic&&supabaseSecretKey);
const stripeConfigured=Boolean(process.env.STRIPE_SECRET_KEY&&process.env.STRIPE_PRO_PRICE_ID);
const stripe=stripeConfigured?new Stripe(process.env.STRIPE_SECRET_KEY):null;
const authClient=hasPublic?createClient(process.env.SUPABASE_URL,supabasePublicKey,{auth:{persistSession:false,autoRefreshToken:false,flowType:'implicit'}}):null;
const admin=hasAdmin?createClient(process.env.SUPABASE_URL,supabaseSecretKey,{auth:{persistSession:false,autoRefreshToken:false}}):null;

function trustedRecoveryOrigin(req){
  const configuredOrigin=new URL(appUrl).origin;
  const raw=String(req.headers.origin||'').trim();
  if(!raw)return configuredOrigin;
  try{
    const candidate=new URL(raw);
    const host=candidate.hostname.toLowerCase();
    const isConfigured=candidate.origin===configuredOrigin;
    const isOwnedPreview=candidate.protocol==='https:'&&(host==='motion-supply-brand-os.vercel.app'||host.endsWith('-motion-supply-co.vercel.app'));
    return isConfigured||isOwnedPreview?candidate.origin:configuredOrigin;
  }catch{return configuredOrigin}
}

app.set('trust proxy',1); app.disable('x-powered-by');
app.use((req,res,next)=>{res.setHeader('X-Request-Id',req.headers['x-request-id']||crypto.randomUUID());res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');res.setHeader('X-Frame-Options','DENY');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'");if(req.path.startsWith('/api/'))res.setHeader('Cache-Control','no-store');if(process.env.NODE_ENV==='production')res.setHeader('Strict-Transport-Security','max-age=31536000; includeSubDomains');next()});
const buckets=new Map(); const RATE_BUCKET_SOFT_LIMIT=5000,RATE_BUCKET_HARD_LIMIT=10000,RATE_BUCKET_MAX_AGE=60*60_000;
function pruneRateBuckets(now){if(buckets.size<RATE_BUCKET_SOFT_LIMIT)return;for(const[k,x]of buckets){if(now-(x.touchedAt||x.start)>RATE_BUCKET_MAX_AGE)buckets.delete(k)}if(buckets.size>RATE_BUCKET_HARD_LIMIT){let remove=buckets.size-RATE_BUCKET_HARD_LIMIT;for(const k of buckets.keys()){buckets.delete(k);if(--remove<=0)break}}}
function limiter(name,windowMs,max){return(req,res,next)=>{const key=`${name}:${req.ip||'unknown'}`,now=Date.now();pruneRateBuckets(now);const x=buckets.get(key)||{count:0,start:now,touchedAt:now};if(now-x.start>windowMs){x.count=0;x.start=now}x.count++;x.touchedAt=now;buckets.set(key,x);if(x.count>max){res.setHeader('Retry-After',Math.max(1,Math.ceil((windowMs-(now-x.start))/1000)));return res.status(429).json({error:'Too many requests. Try again shortly.',code:'RATE_LIMITED'})}next()}}
const apiLimit=limiter('api',60_000,180),authRateLimit=limiter('auth',10*60_000,25),sensitiveLimit=limiter('sensitive',60*60_000,8);

async function userFromRequest(req){if(!admin)return null;const a=req.headers.authorization||'',token=a.startsWith('Bearer ')?a.slice(7):'';if(!token)return null;const {data,error}=await admin.auth.getUser(token);return error?null:data?.user||null}
async function subscriptionForUser(id){if(!admin)return null;const {data}=await admin.from('subscriptions').select('*').eq('user_id',id).maybeSingle();return data||null}
const FREE_LIMITS=Object.freeze({brands:1,skus:5}); const isActiveSub=sub=>Boolean(sub&&['active','trialing'].includes(sub.status)); const hasOpenStripeSub=sub=>Boolean(sub?.stripe_subscription_id&&!['canceled','incomplete_expired'].includes(sub.status));
async function accessForUser(id){const sub=await subscriptionForUser(id);return{sub,active:isActiveSub(sub),plan:isActiveSub(sub)?'pro':'free',limits:isActiveSub(sub)?{brands:null,skus:null}:FREE_LIMITS}}
async function usageForUser(id){if(!admin)return{brands:0,skus:0};const[{count:brands},{count:skus}]=await Promise.all([admin.from('brands').select('*',{count:'exact',head:true}).eq('owner_id',id),admin.from('skus').select('*',{count:'exact',head:true}).eq('owner_id',id)]);return{brands:brands||0,skus:skus||0}}
async function requireProUser(req,res){const user=await userFromRequest(req);if(!user){res.status(401).json({error:'Unauthorized'});return null}const access=await accessForUser(user.id);if(!access.active){res.status(402).json({error:'Brand OS Pro is required for this feature.',code:'PRO_REQUIRED'});return null}return{user,access}}
function safeObject(v,maxKeys=40){if(!v||typeof v!=='object'||Array.isArray(v))return{};const out={};for(const[k,val]of Object.entries(v).slice(0,maxKeys)){if(k.length>80)continue;if(['string','number','boolean'].includes(typeof val)||val===null)out[k]=typeof val==='string'?val.slice(0,1000):val;else if(Array.isArray(val))out[k]=val.slice(0,50);else if(typeof val==='object')out[k]=val}return out}

async function upsertSubscriptionFromStripe(sub,invoiceStatus=null){if(!admin||!sub)return;let userId=sub.metadata?.user_id||null;if(!userId){const{data}=await admin.from('subscriptions').select('user_id').eq('stripe_customer_id',String(sub.customer)).maybeSingle();userId=data?.user_id||null}if(!userId)return;const{data:userData,error:userError}=await admin.auth.admin.getUserById(userId);if(userError||!userData?.user)return;const payload={user_id:userId,stripe_customer_id:String(sub.customer),stripe_subscription_id:sub.id,status:sub.status,price_id:sub.items?.data?.[0]?.price?.id||null,current_period_end:sub.current_period_end?new Date(sub.current_period_end*1000).toISOString():null,cancel_at_period_end:Boolean(sub.cancel_at_period_end),canceled_at:sub.canceled_at?new Date(sub.canceled_at*1000).toISOString():null,trial_end:sub.trial_end?new Date(sub.trial_end*1000).toISOString():null,updated_at:new Date().toISOString()};if(invoiceStatus)payload.latest_invoice_status=invoiceStatus;const{error}=await admin.from('subscriptions').upsert(payload,{onConflict:'user_id'});if(error)throw error}

app.post('/api/stripe-webhook',express.raw({type:'application/json',limit:'256kb'}),async(req,res)=>{if(!stripe||!process.env.STRIPE_WEBHOOK_SECRET||!admin)return res.status(503).send('Billing is not configured.');let event;try{event=stripe.webhooks.constructEvent(req.body,req.headers['stripe-signature'],process.env.STRIPE_WEBHOOK_SECRET)}catch(e){return res.status(400).send(`Webhook Error: ${e.message}`)}let claimed=false;try{claimed=await claimStripeWebhook(admin,event);if(!claimed)return res.json({received:true,duplicate:true});if(['customer.subscription.created','customer.subscription.updated','customer.subscription.deleted'].includes(event.type))await upsertSubscriptionFromStripe(event.data.object);if(event.type==='checkout.session.completed'&&event.data.object.subscription){let sub=await stripe.subscriptions.retrieve(event.data.object.subscription);if(!sub.metadata?.user_id&&event.data.object.metadata?.user_id)sub=await stripe.subscriptions.update(sub.id,{metadata:{...sub.metadata,user_id:event.data.object.metadata.user_id}});await upsertSubscriptionFromStripe(sub)}if(['invoice.paid','invoice.payment_failed'].includes(event.type)&&event.data.object.subscription){const sub=await stripe.subscriptions.retrieve(event.data.object.subscription);await upsertSubscriptionFromStripe(sub,event.type==='invoice.payment_failed'?'payment_failed':'paid')}await completeStripeWebhook(admin,event.id);res.json({received:true})}catch(e){console.error('stripe-webhook',e);if(claimed)await failStripeWebhook(admin,event.id,e);res.status(500).send('Webhook processing failed.')}});

app.use(express.json({limit:'256kb'})); app.use('/api',apiLimit);
app.get('/api/public-config',(req,res)=>res.json({authConfigured:hasPublic&&hasAdmin,cloudConfigured:hasAdmin,billingConfigured:stripeConfigured&&Boolean(process.env.STRIPE_WEBHOOK_SECRET)&&hasAdmin,supportUrl:process.env.SUPPORT_URL||null,privacyUrl:process.env.PRIVACY_URL||null,termsUrl:process.env.TERMS_URL||null}));
app.get('/api/health',(req,res)=>res.json({ok:true,authConfigured:hasPublic&&hasAdmin,cloudConfigured:hasAdmin,billingConfigured:stripeConfigured&&Boolean(process.env.STRIPE_WEBHOOK_SECRET)&&hasAdmin}));
app.post('/api/auth/signup',authRateLimit,async(req,res)=>{if(!authClient)return res.status(503).json({error:'Account service is not configured.'});const email=String(req.body?.email||'').trim().toLowerCase(),password=String(req.body?.password||'');if(!/^\S+@\S+\.\S+$/.test(email)||password.length<8)return res.status(400).json({error:'Use a valid email and a password with at least 8 characters.'});try{const{data,error}=await authClient.auth.signUp({email,password});if(error)return res.status(400).json({error:error.message});res.json({session:data.session||null,user:data.user?{id:data.user.id,email:data.user.email}:null,confirmationRequired:!data.session})}catch(e){console.error('signup',e);res.status(502).json({error:'Could not reach the account service.'})}});
app.post('/api/auth/signin',authRateLimit,async(req,res)=>{if(!authClient)return res.status(503).json({error:'Account service is not configured.'});try{const{data,error}=await authClient.auth.signInWithPassword({email:String(req.body?.email||'').trim().toLowerCase(),password:String(req.body?.password||'')});if(error)return res.status(400).json({error:'Invalid email or password.'});res.json({session:data.session})}catch(e){console.error('signin',e);res.status(502).json({error:'Could not reach the account service.'})}});
app.post('/api/auth/refresh',authRateLimit,async(req,res)=>{if(!authClient)return res.status(503).json({error:'Account service is not configured.'});const token=String(req.body?.refresh_token||'');if(!token)return res.status(400).json({error:'Refresh token required.'});const{data,error}=await authClient.auth.refreshSession({refresh_token:token});if(error)return res.status(401).json({error:'Session expired.'});res.json({session:data.session})});
app.post('/api/auth/recover',sensitiveLimit,async(req,res)=>{if(!authClient)return res.status(503).json({error:'Account service is not configured.'});const email=String(req.body?.email||'').trim().toLowerCase(),redirectOrigin=trustedRecoveryOrigin(req);if(!/^\S+@\S+\.\S+$/.test(email))return res.json({ok:true,message:'If an account exists for that email, a recovery message has been sent.'});try{const{error}=await authClient.auth.resetPasswordForEmail(email,{redirectTo:`${redirectOrigin}/?reset=1`});if(error){console.error('recover-email',{message:error.message,status:error.status||null,code:error.code||null,redirectOrigin});if(error.status===429||String(error.code||'').toLowerCase().includes('rate'))return res.status(429).json({error:'Recovery email limit reached. Wait a few minutes, then request one new link.',code:'RECOVERY_RATE_LIMITED'});return res.status(502).json({error:'Recovery email could not be sent right now. Try again shortly.',code:'RECOVERY_DELIVERY_FAILED'})}return res.json({ok:true,message:'If an account exists for that email, a recovery message has been sent.'})}catch(e){console.error('recover-email',{message:e?.message||String(e),redirectOrigin});return res.status(502).json({error:'Recovery email could not be sent right now. Try again shortly.',code:'RECOVERY_DELIVERY_FAILED'})}});
app.post('/api/auth/update-password',sensitiveLimit,async(req,res)=>{if(!hasPublic)return res.status(503).json({error:'Account service is not configured.'});const authHeader=String(req.headers.authorization||''),token=authHeader.startsWith('Bearer ')?authHeader.slice(7):'';if(!token)return res.status(401).json({error:'Recovery session is invalid or expired.',code:'RECOVERY_SESSION_INVALID'});const password=String(req.body?.password||'');if(password.length<8||password.length>128)return res.status(400).json({error:'Password must be between 8 and 128 characters.'});const{data:userData,error:userError}=await admin.auth.getUser(token);if(userError||!userData?.user)return res.status(401).json({error:'Recovery session is invalid or expired.',code:'RECOVERY_SESSION_INVALID'});const{error}=await admin.auth.admin.updateUserById(userData.user.id,{password});if(error){console.error('update-password',error);return res.status(400).json({error:'Password could not be updated. Request a new recovery link.',code:'PASSWORD_UPDATE_FAILED'})}res.json({ok:true})});

app.get('/api/account',async(req,res)=>{const user=await userFromRequest(req);if(!user)return res.status(401).json({error:'Unauthorized'});const[access,usage]=await Promise.all([accessForUser(user.id),usageForUser(user.id)]);res.json({user:{id:user.id,email:user.email},plan:access.plan,active:access.active,billingManageable:hasOpenStripeSub(access.sub),limits:access.limits,usage})});
app.delete('/api/account',sensitiveLimit,async(req,res)=>{const user=await userFromRequest(req);if(!user)return res.status(401).json({error:'Unauthorized'});if(String(req.body?.confirm||'')!=='DELETE')return res.status(400).json({error:'Confirmation required.',code:'CONFIRM_DELETE'});const sub=await subscriptionForUser(user.id);try{await admin.from('account_deletion_requests').upsert({user_id:user.id,status:'processing',stripe_customer_id:sub?.stripe_customer_id||null,requested_at:new Date().toISOString(),completed_at:null,failure_reason:null},{onConflict:'user_id'});if(stripe&&hasOpenStripeSub(sub))await stripe.subscriptions.cancel(sub.stripe_subscription_id);const{error}=await admin.auth.admin.deleteUser(user.id);if(error)throw error;const{error:auditError}=await admin.from('account_deletion_requests').update({status:'completed',completed_at:new Date().toISOString(),failure_reason:null}).eq('user_id',user.id);if(auditError)console.error('delete-account-audit',auditError);res.json({ok:true})}catch(e){console.error('delete-account',e);await admin.from('account_deletion_requests').update({status:'failed',failure_reason:String(e.message||e).slice(0,500)}).eq('user_id',user.id);res.status(500).json({error:'Account deletion could not be completed. Contact support.',code:'DELETE_FAILED'})}});

app.get('/api/brands',async(req,res)=>{const user=await userFromRequest(req);if(!user)return res.status(401).json({error:'Unauthorized'});const{data,error}=await admin.from('brands').select('*').eq('owner_id',user.id).order('created_at');if(error)return res.status(400).json({error:error.message});res.json({brands:data||[]})});
app.post('/api/brands',async(req,res)=>{const user=await userFromRequest(req);if(!user)return res.status(401).json({error:'Unauthorized'});const access=await accessForUser(user.id);if(!access.active){const usage=await usageForUser(user.id);if(usage.brands>=FREE_LIMITS.brands)return res.status(402).json({error:'Free accounts can save 1 brand. Upgrade to Pro for unlimited brands.',code:'PRO_LIMIT_REACHED'})}const name=String(req.body?.name||'').trim().slice(0,120);if(!name)return res.status(400).json({error:'Brand name is required.'});const{data,error}=await admin.from('brands').insert({owner_id:user.id,name,currency:'USD'}).select().single();if(error)return res.status(400).json({error:error.message});res.json({brand:data})});
app.delete('/api/brands/:id',sensitiveLimit,async(req,res)=>{const user=await userFromRequest(req);if(!user)return res.status(401).json({error:'Unauthorized'});const id=String(req.params.id||'');if(!/^[0-9a-f-]{36}$/i.test(id))return res.status(400).json({error:'Invalid brand.'});const{data:brand,error:lookupError}=await admin.from('brands').select('id,name').eq('id',id).eq('owner_id',user.id).maybeSingle();if(lookupError)return res.status(400).json({error:'Brand could not be loaded.'});if(!brand)return res.status(404).json({error:'Brand not found.'});const{error}=await admin.from('brands').delete().eq('id',id).eq('owner_id',user.id);if(error)return res.status(400).json({error:'Brand could not be deleted.'});res.json({ok:true})});
app.get('/api/skus',async(req,res)=>{const user=await userFromRequest(req);if(!user)return res.status(401).json({error:'Unauthorized'});const{data,error}=await admin.from('skus').select('*').eq('owner_id',user.id).order('created_at');if(error)return res.status(400).json({error:error.message});res.json({skus:data||[]})});
app.post('/api/skus',async(req,res)=>{const user=await userFromRequest(req);if(!user)return res.status(401).json({error:'Unauthorized'});const access=await accessForUser(user.id);if(!access.active){const usage=await usageForUser(user.id);if(usage.skus>=FREE_LIMITS.skus)return res.status(402).json({error:'Free accounts can save up to 5 SKUs. Upgrade to Pro for unlimited SKUs.',code:'PRO_LIMIT_REACHED'})}const brandId=String(req.body?.brand_id||''),sku=String(req.body?.sku||'').trim().slice(0,80),name=String(req.body?.name||'').trim().slice(0,160);const{data:brand}=await admin.from('brands').select('id').eq('id',brandId).eq('owner_id',user.id).maybeSingle();if(!brand)return res.status(403).json({error:'Brand not found.'});if(!sku||!name)return res.status(400).json({error:'SKU and product name are required.'});const retail=Number(req.body?.retail_price),landed=Number(req.body?.landed_cost),onHand=Number(req.body?.on_hand);if(!Number.isFinite(retail)||retail<0)return res.status(400).json({error:'Retail price must be a non-negative number.'});const payload={owner_id:user.id,brand_id:brandId,sku,name,retail_price:retail,landed_cost:Number.isFinite(landed)?Math.max(0,landed):0,on_hand:Number.isFinite(onHand)?Math.max(0,Math.trunc(onHand)):0};const{data,error}=await admin.from('skus').insert(payload).select().single();if(error)return res.status(400).json({error:error.message});res.json({sku:data})});
app.post('/api/import-summaries',async(req,res)=>{const gate=await requireProUser(req,res);if(!gate)return;const payload={owner_id:gate.user.id,brand_id:req.body?.brand_id||null,file_kind:String(req.body?.file_kind||'unknown').slice(0,40),start_date:req.body?.start_date||null,end_date:req.body?.end_date||null,summary:safeObject(req.body?.summary)};const{error}=await admin.from('import_summaries').insert(payload);if(error)return res.status(400).json({error:error.message});res.json({ok:true})});
app.get('/api/entitlement',async(req,res)=>{const user=await userFromRequest(req);if(!user)return res.status(401).json({error:'Unauthorized'});const sub=await subscriptionForUser(user.id),active=isActiveSub(sub);res.json({plan:active?'pro':'free',active,subscription:sub?{status:sub.status,currentPeriodEnd:sub.current_period_end,cancelAtPeriodEnd:Boolean(sub.cancel_at_period_end),trialEnd:sub.trial_end,invoiceStatus:sub.latest_invoice_status}:null})});

const allowedEvents=new Set(['landing_page_viewed','signup_started','signup_completed','onboarding_started','onboarding_step_completed','onboarding_completed','first_calculation_completed','first_recommendation_received','second_session','pro_page_viewed','checkout_started','paid','cancelled','tool_opened','core_activation_completed','meaningful_operating_action','recommendation_actioned','recommendation_ignored','billing_portal_opened','renewal_succeeded','renewal_failed','subscription_recovered']);
app.post('/api/events',limiter('events',60_000,90),async(req,res)=>{if(!admin)return res.status(503).json({error:'Analytics storage is not configured.'});const eventName=String(req.body?.event_name||'').trim();if(!allowedEvents.has(eventName))return res.status(400).json({error:'Unknown event.'});const user=await userFromRequest(req),anonymousId=String(req.body?.anonymous_id||'').trim().slice(0,80)||null,props=safeObject(req.body?.properties,20);const{error}=await admin.from('product_events').insert({user_id:user?.id||null,anonymous_id:anonymousId,event_name:eventName,properties:props});if(error)return res.status(400).json({error:error.message});res.json({ok:true})});
app.get('/api/snapshots',async(req,res)=>{const gate=await requireProUser(req,res);if(!gate)return;const{data,error}=await admin.from('business_snapshots').select('*').eq('owner_id',gate.user.id).order('captured_at',{ascending:false}).limit(52);if(error)return res.status(400).json({error:error.message});res.json({snapshots:data||[]})});
app.post('/api/snapshots',async(req,res)=>{const gate=await requireProUser(req,res);if(!gate)return;const{data:row,error}=await admin.from('business_snapshots').insert({owner_id:gate.user.id,brand_id:req.body?.brand_id||null,data:safeObject(req.body?.data)}).select().single();if(error)return res.status(400).json({error:error.message});res.json({snapshot:row})});
app.get('/api/recommendations',async(req,res)=>{const gate=await requireProUser(req,res);if(!gate)return;const{data,error}=await admin.from('recommendation_history').select('*').eq('owner_id',gate.user.id).order('created_at',{ascending:false}).limit(100);if(error)return res.status(400).json({error:error.message});res.json({recommendations:data||[]})});
app.post('/api/recommendations',async(req,res)=>{const gate=await requireProUser(req,res);if(!gate)return;const title=String(req.body?.title||'').trim().slice(0,180),ruleKey=String(req.body?.rule_key||'').trim().slice(0,80),priority=String(req.body?.priority||'medium').toLowerCase();if(!title||!ruleKey)return res.status(400).json({error:'Recommendation title and rule key are required.'});if(!['low','medium','high'].includes(priority))return res.status(400).json({error:'Invalid priority.'});const{data,error}=await admin.from('recommendation_history').insert({owner_id:gate.user.id,brand_id:req.body?.brand_id||null,rule_key:ruleKey,priority,title,evidence:safeObject(req.body?.evidence)}).select().single();if(error)return res.status(400).json({error:error.message});res.json({recommendation:data})});

app.get('/api/business-memory',async(req,res)=>{const gate=await requireProUser(req,res);if(!gate)return;let q=admin.from('business_memory').select('*').eq('owner_id',gate.user.id).order('updated_at',{ascending:false}).limit(200);if(req.query.brand_id)q=q.eq('brand_id',String(req.query.brand_id));const{data,error}=await q;if(error)return res.status(400).json({error:error.message});res.json({memory:data||[]})});
app.put('/api/business-memory/:key',async(req,res)=>{const gate=await requireProUser(req,res);if(!gate)return;const key=String(req.params.key||'').trim().slice(0,80),brandId=req.body?.brand_id||null;if(!key)return res.status(400).json({error:'Memory key required.'});if(brandId){const{data:brand}=await admin.from('brands').select('id').eq('id',brandId).eq('owner_id',gate.user.id).maybeSingle();if(!brand)return res.status(403).json({error:'Brand not found.'})}const payload={owner_id:gate.user.id,brand_id:brandId,memory_key:key,value:safeObject(req.body?.value),source:'user',updated_at:new Date().toISOString()};const{data,error}=await admin.from('business_memory').upsert(payload,{onConflict:'owner_id,brand_id,memory_key'}).select().single();if(error)return res.status(400).json({error:error.message});res.json({memory:data})});
app.delete('/api/business-memory/:id',async(req,res)=>{const gate=await requireProUser(req,res);if(!gate)return;const{error}=await admin.from('business_memory').delete().eq('id',String(req.params.id)).eq('owner_id',gate.user.id);if(error)return res.status(400).json({error:error.message});res.json({ok:true})});

app.post('/api/create-checkout-session',sensitiveLimit,async(req,res)=>{if(!stripe||!admin)return res.status(503).json({error:'Billing is not configured yet.'});const user=await userFromRequest(req);if(!user)return res.status(401).json({error:'Sign in first.'});try{const existing=await subscriptionForUser(user.id);if(isActiveSub(existing))return res.status(409).json({error:'You already have an active Pro subscription.',code:'ALREADY_PRO'});if(hasOpenStripeSub(existing))return res.status(409).json({error:'Your existing subscription needs attention. Open billing to manage it.',code:'BILLING_RECOVERY_REQUIRED'});let customerId=existing?.stripe_customer_id||null;if(!customerId){const c=await stripe.customers.create({email:user.email,metadata:{user_id:user.id}});customerId=c.id;await admin.from('subscriptions').upsert({user_id:user.id,stripe_customer_id:customerId,status:'inactive',updated_at:new Date().toISOString()},{onConflict:'user_id'})}const s=await stripe.checkout.sessions.create({mode:'subscription',customer:customerId,line_items:[{price:process.env.STRIPE_PRO_PRICE_ID,quantity:1}],success_url:`${appUrl}/?billing=success&session_id={CHECKOUT_SESSION_ID}`,cancel_url:`${appUrl}/?billing=cancel`,client_reference_id:user.id,metadata:{user_id:user.id},subscription_data:{metadata:{user_id:user.id}},allow_promotion_codes:true,wallet_options:{link:{display:'never'}}});res.json({url:s.url})}catch(e){console.error('checkout',e);res.status(500).json({error:'Could not start checkout.'})}});
app.post('/api/create-portal-session',sensitiveLimit,async(req,res)=>{if(!stripe||!admin)return res.status(503).json({error:'Billing is not configured yet.'});const user=await userFromRequest(req);if(!user)return res.status(401).json({error:'Sign in first.'});const existing=await subscriptionForUser(user.id);if(!existing?.stripe_customer_id)return res.status(400).json({error:'No billing profile found.'});try{const s=await stripe.billingPortal.sessions.create({customer:existing.stripe_customer_id,return_url:appUrl});res.json({url:s.url})}catch(e){console.error('portal',e);res.status(500).json({error:'Could not open billing portal.'})}});

app.use('/api',(req,res)=>res.status(404).json({error:'API route not found.',code:'API_NOT_FOUND'}));
app.use(express.static(path.join(__dirname,'public'),{extensions:['html'],maxAge:process.env.NODE_ENV==='production'?'1h':0}));
app.use((req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.use((err,req,res,next)=>{console.error('unhandled',err);if(res.headersSent)return next(err);res.status(500).json({error:'Unexpected server error.',code:'INTERNAL_ERROR'})});
app.listen(port,()=>console.log(`Motion Supply Brand OS running on ${appUrl}`));