-- Motion Supply Brand OS V5.5 migration
-- Run once in Supabase SQL Editor before deploying V5.5 server code.

create table if not exists public.business_snapshots (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  brand_id uuid,
  data jsonb not null default '{}'::jsonb,
  captured_at timestamptz not null default now(),
  constraint business_snapshots_brand_owner_fk foreign key (brand_id, owner_id) references public.brands(id, owner_id) on delete cascade
);
create index if not exists business_snapshots_owner_time_idx on public.business_snapshots(owner_id, captured_at desc);

create table if not exists public.recommendation_history (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  brand_id uuid,
  rule_key text not null check (char_length(rule_key) between 1 and 80),
  priority text not null default 'medium' check (priority in ('low','medium','high')),
  title text not null check (char_length(title) between 1 and 180),
  evidence jsonb not null default '{}'::jsonb,
  status text not null default 'open' check (status in ('open','acted','dismissed')),
  created_at timestamptz not null default now(),
  constraint recommendation_history_brand_owner_fk foreign key (brand_id, owner_id) references public.brands(id, owner_id) on delete cascade
);
create index if not exists recommendation_history_owner_time_idx on public.recommendation_history(owner_id, created_at desc);

create table if not exists public.product_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  anonymous_id text,
  event_name text not null check (char_length(event_name) between 1 and 80),
  properties jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists product_events_name_time_idx on public.product_events(event_name, created_at desc);
create index if not exists product_events_user_time_idx on public.product_events(user_id, created_at desc);

alter table public.business_snapshots enable row level security;
alter table public.recommendation_history enable row level security;
alter table public.product_events enable row level security;

-- Shopify aggregate history is a Pro cloud feature.
drop policy if exists "import summaries own rows" on public.import_summaries;
drop policy if exists "import summaries pro inserts" on public.import_summaries;
create policy "import summaries own rows" on public.import_summaries for select to authenticated
using ((select auth.uid()) = owner_id);
create policy "import summaries pro inserts" on public.import_summaries for insert to authenticated
with check ((select auth.uid()) = owner_id and exists (
  select 1 from public.subscriptions s where s.user_id=(select auth.uid()) and s.status in ('active','trialing')
));

drop policy if exists "snapshots own rows" on public.business_snapshots;
drop policy if exists "snapshots pro rows" on public.business_snapshots;
create policy "snapshots pro rows" on public.business_snapshots for all to authenticated
using ((select auth.uid()) = owner_id and exists (
  select 1 from public.subscriptions s where s.user_id=(select auth.uid()) and s.status in ('active','trialing')
))
with check ((select auth.uid()) = owner_id and exists (
  select 1 from public.subscriptions s where s.user_id=(select auth.uid()) and s.status in ('active','trialing')
));

drop policy if exists "recommendations own rows" on public.recommendation_history;
drop policy if exists "recommendations pro rows" on public.recommendation_history;
create policy "recommendations pro rows" on public.recommendation_history for all to authenticated
using ((select auth.uid()) = owner_id and exists (
  select 1 from public.subscriptions s where s.user_id=(select auth.uid()) and s.status in ('active','trialing')
))
with check ((select auth.uid()) = owner_id and exists (
  select 1 from public.subscriptions s where s.user_id=(select auth.uid()) and s.status in ('active','trialing')
));

revoke all on public.business_snapshots, public.recommendation_history, public.product_events from anon;
grant select, insert, update, delete on public.business_snapshots, public.recommendation_history to authenticated;
revoke all on public.product_events from authenticated;
